FlootIgnoreItems = {								-- Don't show these items.
	["Emblem of Heroism"] = "Vasago",
	["Emblem of Valor"] = "Vasago",
	["Emblem of Conquest"] = "Presco",
	["Emblem of Triumph"] = "Presco",
	["Runed Orb"] = "Presco",
	["Crusader Orb"] = "Presco",
	["Primordial Saronite"] = "Presco",
	["Fish Oil"] = "Presco",					-- Test Item
	["Encrusted Basilisk Skin"] = "Presco",		-- Test Item
	["Basilisk Liver"] = "Presco",				-- Test item
	["Fur Clothing Scraps"] = "Presco",			-- Test item
	["Thick Fur Clothing Scraps"] = "Presco",	-- Test item
}

FlootAutoLootItems = {							-- Autoloot if found
	["Emblem of Heroism"] = "Vasago",
	["Emblem of Valor"] = "Vasago",
	["Emblem of Conquest"] = "Presco",
	["Emblem of Triumph"] = "Presco",
	["Fish Oil"] = "Presco",					-- Test Item
	["Encrusted Basilisk Skin"] = "Presco",		-- Test Item
	["Basilisk Liver"] = "Presco",				-- Test item
	["Fur Clothing Scraps"] = "Presco",			-- Test item
	["Thick Fur Clothing Scraps"] = "Presco",	-- Test item
}

FlootAutoBankItems = {							-- Auto bank if found
	["Crusader Orb"] = "Presco",
	["Runed Orb"] = "Presco",
	["Primordial Saronite"] = "Presco",
	["Living Ember"] = "Presco",
}

FlootListType = {
	["Conqueror's Mark of Sanctification"] = "Tier10",
	["Protector's Mark of Sanctification"] = "Tier10",
	["Vanquisher's Mark of Sanctification"] = "Tier10",
	["52028"] = "Tier10h", -- Heroic Vanquisher's Mark of Sanctification
	["52029"] = "Tier10h", -- Heroic Protector's Mark of Sanctification
	["52030"] = "Tier10h", -- Heroic Conqueror's Mark of Sanctification
	["64314"] = "Tier11", -- Rogue,Mage,DK,Druid Shoulder
	["63682"] = "Tier11", -- Rogue,Mage,DK,Druid Helm
	["65001"] = "Tier11", -- Pala,Priest,Warlock Helm
	["64315"] = "Tier11", -- Pala,Priest,Warlock Shoulder
	["65000"] = "Tier11", -- Warrior,Hunter,Shaman Helm
	["64316"] = "Tier11", -- Warrior,Hunter,Shaman Shoulder
	["67431"] = "Tier11h", -- Rogue,Mage,DK,Druid Hands
	["67425"] = "Tier11h", -- Rogue,Mage,DK,Druid Chest
	["67426"] = "Tier11h", -- Rogue,Mage,DK,Druid Legs
	["65002"] = "Tier11h", -- Rogue,Mage,DK,Druid Helm
	["65089"] = "Tier11h", -- Rogue,Mage,DK,Druid Shoulder
	["67429"] = "Tier11h", -- Pala,Priest,Warlock Hands
	["67423"] = "Tier11h", -- Pala,Priest,Warlock Chest
	["67428"] = "Tier11h", -- Pala,Priest,Warlock Legs
	["65001"] = "Tier11h", -- Pala,Priest,Warlock Helm
	["65088"] = "Tier11h", -- Pala,Priest,Warlock Shoulder
	["67430"] = "Tier11h", -- Warrior,Hunter,Shaman Hands
	["67424"] = "Tier11h", -- Warrior,Hunter,Shaman Chest
	["67427"] = "Tier11h", -- Warrior,Hunter,Shaman Legs
	["65000"] = "Tier11h", -- Warrior,Hunter,Shaman Helm
	["65087"] = "Tier11h", -- Warrior,Hunter,Shaman Shoulder
	["66998"] = "Tier11h", -- Token for any class for any item.
	["63684"] = "Tier11", -- warrior, Hunter, sshaman, shoulder.
	["Embersilk Cloth"] = "Tier11h", -- Test item.
	["Dragon Flank"] = "Tier12", -- Test item.
	["71682"] = "Tier12", -- Warrior, hunter, Shaman
	["71683"] = "Tier12h", -- Warrior, hunter, Shaman
	["71684"] = "Tier12h", -- Warrior, hunter, Shaman
	["71685"] = "Tier12h", -- Warrior, hunter, Shaman
	["71686"] = "Tier12h", -- Warrior, hunter, Shaman
	["71687"] = "Tier12h", -- Warrior, hunter, Shaman
	["71688"] = "Tier12", -- Warrior, hunter, Shaman
	["71675"] = "Tier12", -- Paladin, Priest, Warlock
	["71676"] = "Tier12h", -- Paladin, Priest, Warlock
	["71677"] = "Tier12h", -- Paladin, Priest, Warlock
	["71678"] = "Tier12h", -- Paladin, Priest, Warlock
	["71679"] = "Tier12h", -- Paladin, Priest, Warlock
	["71680"] = "Tier12h", -- Paladin, Priest, Warlock
	["71681"] = "Tier12", -- Paladin, Priest, Warlock
	["71668"] = "Tier12", -- Death Knight, Druid, Mage, Rogue
	["71669"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71670"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71671"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71672"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71673"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71674"] = "Tier12", -- Death Knight, Druid, Mage, Rogue
}

FlootRaidBosses = { 
	["Beth'tilac"] = true,  -- Firelands
	["Lord Rhyolith"] = true,
	["Alysrazor"] = true,
	["Shannox"] = true,
	["Baleroc"] = true,
	["Majordomo Staghelm"] = true,
	["Ragnaros"] = true,
	["Argaloth"] = true, -- Baradin Hold
	["Occu'thar"] = true,
	["Magmaw"] = true, -- Blackwing Descent
	["Arcanotron"] = true,
	["Electron"] = true,
	["Magmatron"] = true,
	["Taxitron"] = true,
	["Chimaeron"] = true,
	["Maloriak"] = true,
	["Attramedes"] = true,
	["Nefarian"] = true,
	["Halfus Wyrmbreaker"] = true, -- The Bastion of Twilight
	["Theralion"] = true,
	["Valiona"] = true,
	["Cho'gall"] = true,
	["Sinestra"] = true,
	["Al'Akir"] = true, -- Thrones of the four winds Missing Conclave names
	["Obsidian Charscale"] = true, -- Test mob
	["Obsidian Viletongue"] = true, -- Test mob
}
