FlootIgnoreItems = {								-- Don't show these items.
	["Emblem of Heroism"] = "Vasago",
	["Emblem of Valor"] = "Vasago",
	["Emblem of Conquest"] = "Presco",
	["Emblem of Triumph"] = "Presco",
	["Runed Orb"] = "Presco",
	["Crusader Orb"] = "Presco",
	["Primordial Saronite"] = "Presco",
	["Fish Oil"] = "Presco",					-- Test Item
	["Encrusted Basilisk Skin"] = "Presco",		-- Test Item
	["Basilisk Liver"] = "Presco",				-- Test item
	["Fur Clothing Scraps"] = "Presco",			-- Test item
	["Thick Fur Clothing Scraps"] = "Presco",	-- Test item
}

FlootAutoLootItems = {							-- Autoloot if found
	["Emblem of Heroism"] = "Vasago",
	["Emblem of Valor"] = "Vasago",
	["Emblem of Conquest"] = "Presco",
	["Emblem of Triumph"] = "Presco",
	["Fish Oil"] = "Presco",					-- Test Item
	["Encrusted Basilisk Skin"] = "Presco",		-- Test Item
	["Basilisk Liver"] = "Presco",				-- Test item
	["Fur Clothing Scraps"] = "Presco",			-- Test item
	["Thick Fur Clothing Scraps"] = "Presco",	-- Test item
}

FlootAutoBankItems = {							-- Auto bank if found
	["Crusader Orb"] = "Presco",
	["Runed Orb"] = "Presco",
	["Primordial Saronite"] = "Presco",
	["Living Ember"] = "Presco",
}

FlootListType = {
	["Conqueror's Mark of Sanctification"] = "Tier10",
	["Protector's Mark of Sanctification"] = "Tier10",
	["Vanquisher's Mark of Sanctification"] = "Tier10",
	["52028"] = "Tier10h", -- Heroic Vanquisher's Mark of Sanctification
	["52029"] = "Tier10h", -- Heroic Protector's Mark of Sanctification
	["52030"] = "Tier10h", -- Heroic Conqueror's Mark of Sanctification
	["64314"] = "Tier11", -- Rogue,Mage,DK,Druid Shoulder
	["63682"] = "Tier11", -- Rogue,Mage,DK,Druid Helm
	["65001"] = "Tier11", -- Pala,Priest,Warlock Helm
	["64315"] = "Tier11", -- Pala,Priest,Warlock Shoulder
	["65000"] = "Tier11", -- Warrior,Hunter,Shaman Helm
	["64316"] = "Tier11", -- Warrior,Hunter,Shaman Shoulder
	["67431"] = "Tier11h", -- Rogue,Mage,DK,Druid Hands
	["67425"] = "Tier11h", -- Rogue,Mage,DK,Druid Chest
	["67426"] = "Tier11h", -- Rogue,Mage,DK,Druid Legs
	["65002"] = "Tier11h", -- Rogue,Mage,DK,Druid Helm
	["65089"] = "Tier11h", -- Rogue,Mage,DK,Druid Shoulder
	["67429"] = "Tier11h", -- Pala,Priest,Warlock Hands
	["67423"] = "Tier11h", -- Pala,Priest,Warlock Chest
	["67428"] = "Tier11h", -- Pala,Priest,Warlock Legs
	["65001"] = "Tier11h", -- Pala,Priest,Warlock Helm
	["65088"] = "Tier11h", -- Pala,Priest,Warlock Shoulder
	["67430"] = "Tier11h", -- Warrior,Hunter,Shaman Hands
	["67424"] = "Tier11h", -- Warrior,Hunter,Shaman Chest
	["67427"] = "Tier11h", -- Warrior,Hunter,Shaman Legs
	["65000"] = "Tier11h", -- Warrior,Hunter,Shaman Helm
	["65087"] = "Tier11h", -- Warrior,Hunter,Shaman Shoulder
	["66998"] = "Tier11h", -- Token for any class for any item.
	["63684"] = "Tier11", -- warrior, Hunter, sshaman, shoulder.
	["Embersilk Cloth"] = "Tier11h", -- Test item.
	["Dragon Flank"] = "Tier12", -- Test item.
	["71682"] = "Tier12", -- Warrior, hunter, Shaman
	["71683"] = "Tier12h", -- Warrior, hunter, Shaman
	["71684"] = "Tier12h", -- Warrior, hunter, Shaman
	["71685"] = "Tier12h", -- Warrior, hunter, Shaman
	["71686"] = "Tier12h", -- Warrior, hunter, Shaman
	["71687"] = "Tier12h", -- Warrior, hunter, Shaman
	["71688"] = "Tier12", -- Warrior, hunter, Shaman
	["71675"] = "Tier12", -- Paladin, Priest, Warlock
	["71676"] = "Tier12h", -- Paladin, Priest, Warlock
	["71677"] = "Tier12h", -- Paladin, Priest, Warlock
	["71678"] = "Tier12h", -- Paladin, Priest, Warlock
	["71679"] = "Tier12h", -- Paladin, Priest, Warlock
	["71680"] = "Tier12h", -- Paladin, Priest, Warlock
	["71681"] = "Tier12", -- Paladin, Priest, Warlock
	["71668"] = "Tier12", -- Death Knight, Druid, Mage, Rogue
	["71669"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71670"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71671"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71672"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71673"] = "Tier12h", -- Death Knight, Druid, Mage, Rogue
	["71674"] = "Tier12", -- Death Knight, Druid, Mage, Rogue
	["89237"] = "Tier14", -- Paladin Priest Warlock -- Chest Normal 10 man
	["89238"] = "Tier14", -- Warrior Hunter Shaman Monk
	["89239"] = "Tier14", -- Rogue Death Kknight Mage Druid
	["89240"] = "Tier14", -- paladin Priest Warlock -- Gloves Normal 10 man
	["89241"] = "Tier14", -- Warrior, Hunter, Shaman, Monk
	["89242"] = "Tier14", -- Rogue, Death Knight, Mage Druid
	["89243"] = "Tier14", -- Paladin Priest Warlock -- Legs Normal 10 man
	["89244"] = "Tier14", -- Warrior, Hunter, Shaman, Monk
	["89245"] = "Tier14", -- Rogue, Death Knight, Mage, Druid
	["89235"] = "Tier14", -- Paladin, Priest, Warlock -- Helmet Normal 10 man
	["89236"] = "Tier14", -- Warrior, Hunter, Shaman, Monk
	["89234"] = "Tier14", -- Rogue, Death Knight, Mage Druid
	["89246"] = "Tier14", -- Paladin, Priest, Warlock -- Shoulder Normal 10 man
	["89247"] = "Tier14", -- Warrior, Hunter, Shaman, Monk
	["89248"] = "Tier14", -- Rogue, Death Knight, Mage, Druid
	["89250"] = "Tier14h", -- Paladin, Priest, Warlock  -- Chest Heroic 10 man
	["89251"] = "Tier14h", -- Warrior, Hunter, Shaman, Monk
	["89249"] = "Tier14h", -- Rogue, Death Knight, Mage, Druid
	["89256"] = "Tier14h", -- Paladin, Priest, Warlock -- Gloves Heroic 10 man
	["89257"] = "Tier14h", -- Warrior, Hunter, Shaman, Monk
	["89255"] = "Tier14h", -- Rogue, Death Knight, Mage, Druid
	["89253"] = "Tier14h", -- Paladin, Priest, Warlock -- Pants Heroic 10 man
	["89254"] = "Tier14h", -- Warrio, Hunter, Shaman, Monk
	["89252"] = "Tier14h", -- Rogue, Death Knight, Mage, Druid
	["89259"] = "Tier14h", -- Paladin, Priest, Warlock -- Helmet Heroic 10 man
	["89260"] = "Tier14h", -- Warrior, Hunter, Shaman, Monk
	["89258"] = "Tier14h", -- Rogue, Death Knight, Mage, Druid
	["89262"] = "Tier14h", -- Paladin, Priest, Warlock -- Shoulder Heroic 10 man
	["89263"] = "Tier14h", -- Warrior, Hunter, Shaman, Monk
	["89261"] = "Tier14h", -- Rogue, Death Knight, Mage, Druid
	["95574"] = "Tier15", -- Paladin, Priest, Warlock -- Chest Normal 10 man
	["95579"] = "Tier15", -- Warrior, Hunter, Shaman, Monk
	["95569"] = "Tier15", -- Rogue, Death Knight, Mage, Druid
	["95575"] = "Tier15", -- Paladin, Priest, Warlock -- Gloves Normal 10 man
	["95580"] = "Tier15", -- Warrior, Hunter, Shaman, Monk
	["95570"] = "Tier15", -- Rogue, Death Knight, Mage, Druid
	["95577"] = "Tier15", -- Paladin, Priest, Warlock -- Helmet Normal 10 man
	["95582"] = "Tier15", -- Warrior, Hunter, Shaman, Monk
	["95571"] = "Tier15", -- Rogue, Death Knight, Mage, Druid
	["95576"] = "Tier15", -- Paladin, Priest, Warlock -- Pants Normal 10 man
	["95581"] = "Tier15", -- Warrior, Hunter, Shaman, Monk
	["95572"] = "Tier15", -- Rogue, Death Knight, Mage, Druid
	["95578"] = "Tier15", -- Paladin, Priest, Warlock -- Shoulders Normal 10 man
	["95583"] = "Tier15", -- Warrior, Hunter, Shaman, Monk
	["95573"] = "Tier15", -- Rogue, Death Knight, Mage, Druid
	["96567"] = "Tier15h", -- Paladin, Priest, Warlock -- Chest Heroic 10 man
	["96568"] = "Tier15h", -- Warrior, Hunter, Shaman, Monk
	["96566"] = "Tier15h", -- Rogue, Death Knight, Mage, Druid
	["96600"] = "Tier15h", -- Paladin, Priest, Warlock -- Gloves Heroic 10 man
	["96601"] = "Tier15h", -- Warrior, Hunter, Shaman, Monk
	["96599"] = "Tier15h", -- Rogue, Death Knight, Mage, Druid
	["96624"] = "Tier15h", -- Paladin, Priest, Warlock -- Helmet Heroic 10 man
	["96625"] = "Tier15h", -- Warrior, Hunter, Shaman, Monk
	["96623"] = "Tier15h", -- Rogue, Death Knight, Mage, Druid
	["96632"] = "Tier15h", -- Paladin, Priest, Warlock -- Pants Heroic 10 man
	["96633"] = "Tier15h", -- Warrior, Hunter, Shaman, Monk
	["96631"] = "Tier15h", -- Rogue, Death Knight, Mage, Druid
	["96700"] = "Tier15h", -- Paladin, Priest, Warlock -- Shoulder Heroic 10 man
	["96701"] = "Tier15h", -- Warrior, Hunter, Shaman, Monk
	["96699"] = "Tier15h", -- Rogue, Death Knight, Mage, Druid

}

FlootRaidBosses = { 
	["Beth'tilac"] = true,  -- Firelands
	["Lord Rhyolith"] = true,
	["Alysrazor"] = true,
	["Shannox"] = true,
	["Baleroc"] = true,
	["Majordomo Staghelm"] = true,
	["Ragnaros"] = true,
	["Argaloth"] = true, -- Baradin Hold
	["Occu'thar"] = true,
	["Magmaw"] = true, -- Blackwing Descent
	["Arcanotron"] = true,
	["Electron"] = true,
	["Magmatron"] = true,
	["Taxitron"] = true,
	["Chimaeron"] = true,
	["Maloriak"] = true,
	["Attramedes"] = true,
	["Nefarian"] = true,
	["Halfus Wyrmbreaker"] = true, -- The Bastion of Twilight
	["Theralion"] = true,
	["Valiona"] = true,
	["Cho'gall"] = true,
	["Sinestra"] = true,
	["Al'Akir"] = true, -- Thrones of the four winds Missing Conclave names
	["Imperial Vizier Zor'lok"] = true, -- Heart of Fear
	["Blade Lord Ta'yak"] = true,
	["Garalon"] = true,
	["Wind Lord Mel'jarak"] = true,
	["Amber-Shaper Un'sok"] = true,
	["Amber Monstrosity"] = true,
	["Grand Empress Shek'zeer"] = true,
	["Amethyst Guardian"] = true, -- Mogu'shan Vaults
	["Cobalt Guardian"] = true,
	["Jade Guardian"] = true,
	["Jasper Guardian"] = true,
	["Feng the Accursed"] = true,
	["Gara'jal the Spiritbinder"] = true,
	["Meng the Demented"] = true,
	["Qiang the Merciless"] = true,
	["Subetai the Swift"] = true,
	["Zian of the Endless Shadow"] = true,
	["Elegon"] = true,
	["Jan-xi"] = true,
	["Qin-xi"] = true,
	["Sha of Anger"] = true, -- Pandarian world bosses
	["Galleon"] = true,
	["Chief Salyis"] = true,
	["Nalak"] = true,
	["Oondasta"] = true,
	["Protector Kaolan"] = true, -- Terrace of Endless spring
	["Elder Regail"] = true,
	["Elder Asani"] = true,
	["Tsulong"] = true,
	["Lei Shi"] = true,
	["Sha of Fear"] = true,
	["Jin'rokh the Breaker"] = true, -- Throne of Thunder
	["Horridon"] = true,
	["Kazra'jin"] = true,
	["Sul the Sandcrawler"] = true,
	["Frost King Malakk"] = true,
	["High Priestess Mar'li"] = true,
	["Tortos"] = true,
	["Megaera"] = true,
	["Flaming Head"] = true,
	["Venomous Head"] = true,
	["Frozen Head"] = true,
	["Ji-Kun"] = true,
	["Durumu"] = true,
	["Primordius"] = true,
	["Dark Animus"] = true,
	["Iron Qon"] = true,
	["Ro'Shak"] = true,
	["Quet'zal"] = true,
	["Dam'ren"] = true,
	["Lu'lin"] = true,
	["Suen"] = true,
	["Lei Shen"] = true,
}
